### ISSUE TITLE
nginx log

### ISSUE THREAD

**Issue by InCogNiTo124** [flashspys/docker-nginx-static#16]
Hello,

I have successfuly deployed my static app as a docker container using this image. However, running `sudo docker logs ${my_container}` returns no output.

By manually exploring the container, `/var/log/nginx/access.log` seems to be a link to `stdout`.

What should I do to get logs?

**Comment by flashspys** [comment]
Hey, 
thanks for using this image!

The default [nginx.conf](https://github.com/flashspys/docker-nginx-static/blob/master/nginx.conf) in this image disables the access.log. Please add a modfied version to your image similar to [the process of adding a custom default.conf](https://github.com/flashspys/docker-nginx-static#custom-nginx-config). The path, where the nginx.conf is located, is `/etc/nginx/nginx.conf`

**Comment by InCogNiTo124** [comment]
I will explain my solution for anyone in the future:

I made a file `default.conf` with this content:
```
server {
    listen       80;
    server_name  localhost;
    location / {
        root   /static;
        index  index.html index.htm;
    }
    access_log /dev/stdout;
    error_log /dev/stderr;
}
```
You can basically copy/paste this.

Then, I made one simple change in my `docker-compose.yml`
```
services:
  my-service:
    image: ...
    labels: ... # traefik v2 stuff
    ports: ...
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
```

This works automagically, and `sudo docker logs` returns proper logs now.
