### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by codingsett** [flashspys/docker-nginx-static#5]
Hello, i started using this image with traefik but i keep getting 404 errors on my site and i cant figure why?

Here is my docker-compose file.
```
services:
  stats:
    image: flashspys/nginx-static
    container_name: stats
    networks:
      
      - web
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.backend=stats
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:stats.io
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
    volumes: 
      - /staticfiles:/root/dist
```
